  ## Configure additional grafana datasources
  ## ref: http://docs.grafana.org/administration/provisioning/#datasources
prometheus:
  prometheusSpec:
    retention: 3d
    serviceMonitorNamespaceSelector: {} ### Namespace for ServiceMonitors select
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {} ### matchLabels for ServiceMonitors select
  service:
    nodePort: 31060
grafana:
  adminPassword: admin
  additionalDataSources:
    - name: loki
      type: loki
      url: http://loki:3100